ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensor/2.0/core
ccflags-y += -I$(srctree)/drivers/misc/mediatek/scp/include

oplus_bsp_sensor_feedback-y := sensor_feedback.o
obj-$(CONFIG_OPLUS_SENSOR_FB_MTK)	+= oplus_bsp_sensor_feedback.o
