#
# Makefile for the touchscreen drivers.
#

ccflags-y += -Wall

# Each configuration option enables a list of files.
obj-$(CONFIG_TOUCHPANEL_SYNAPTICS_TD4160)  +=  synaptics_tcm_core.o \
						 synaptics_tcm_device.o \
						 synaptics_tcm_recovery.o \
						 synaptics_tcm_zeroflash.o
#endif
