# # SPDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2020-2022 Oplus. All rights reserved.
#
# Makefile for the OPLUS Linux Kernel zram opt.
#

obj-$(CONFIG_OPLUS_FEATURE_ZRAM_OPT) 	+= zram_opt.o
