#ifdef CONFIG_OPLUS_KERNEL_SECURE_FEATURE
obj-$(CONFIG_OPLUS_KERNEL_SECURE_KEVENTUPLOAD)	 +=  oplus_security_keventupload.o
oplus_security_keventupload-objs := oplus_kevent_upload.o oplus_secure_debug.o
#endif /* CONFIG_OPLUS_KERNEL_SECURE_FEATURE */