obj-$(CONFIG_TOUCHPANEL_CHIPONE) += chipone.o

chipone-objs += cts_core.o
chipone-objs += cts_sfctrlv2.o
chipone-objs += cts_spi_flash.o
chipone-objs += cts_firmware.o
chipone-objs += cts_tool.o
chipone-objs += cts_sysfs.o
chipone-objs += cts_test.o
chipone-objs += cts_strerror.o
chipone-objs += cts_vendor_driver.o
